### ISSUE TITLE
Can't use Nifi 2.0.0-M4 after copy Daffodil nar file into /lib

### ISSUE THREAD

**Issue by Covrigaru** [OwlCyberDefense/nifi-daffodil#18]
I installed Nifi 2.0.0-M4 top Ubuntu 22.04 LTS with Java 21.0.4+7 and tried to use Daffodil.

I tried a few options, I downloaded the nar file https://github.com/OwlCyberDefense/nifi-daffodil/releases and copied to nifi/lib/
I tried the latest version 1.18 , I also tried with version 1.17, I got the same issue.
I cloned https://github.com/OwlCyberDefense/nifi-daffodil.git built the nar file locally and copied to nifi/lib/ I got the same issue.

"failed to load extension type. You may not be able to create new processors, controllers, services, reporting tasks, parameters or flow analysis ..."

When I pull a new processor, I can't get any processor in the list.
I checked the nifi-user.log I see that there is an issue while trying to initialize class com.owlcyberdefense.processors.DaffodilUnparse

![image](https://github.com/user-attachments/assets/b784690f-bd63-4587-8cd7-a7044351eed3)

**Comment by stevedlawrence** [comment]
@Covrigaru , thanks for reporting this. I just released [v1.19](https://github.com/OwlCyberDefense/nifi-daffodil/releases/tag/v1.19) which should work with the NiFi 2.x.
